exclude = [".git", ".venv", ".vscode", ".devcontainer", "docker"]
line-length = 79
indent-width = 4
target-version = "py311"

[lint]
extend-select = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
